### ISSUE TITLE
undefined method p for OpenSSL::PKey::DH

### ISSUE THREAD

**Issue by wbotelhos** [net-ssh/net-ssh#535]
Hi,

I'm using knife solo and it is running an error.

## Versions

`net-ssh (3.2.0)`
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`

### Command

```bash
knife solo prepare ubuntu@xx.xxx.xxx.xxx nodes/xx.xxx.xxx.xxx.json
```

## Error

```bash
INFO: Using configuration from /Users/wbotelhos/workspace/app-chef/.chef/knife.rb
Bootstrapping Chef...
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
/Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:118:in `generate_key': undefined method `p=' for #<OpenSSL::PKey::DH:0x007fc378b32480> (NoMethodError)
Did you mean?  p
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:51:in `initialize'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:362:in `new'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:362:in `exchange_keys'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:206:in `proceed!'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/algorithms.rb:154:in `accept_kexinit'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `new'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/net-ssh-3.2.0/lib/net/ssh.rb:232:in `start'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/knife-solo/ssh_connection.rb:42:in `session'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/knife-solo/ssh_command.rb:153:in `try_connection'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/knife-solo/ssh_command.rb:194:in `detect_authentication_method'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/knife-solo/ssh_command.rb:290:in `run_command'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/chef/knife/solo_prepare.rb:71:in `operating_system'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/chef/knife/solo_prepare.rb:67:in `bootstrap'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/knife-solo-0.6.0/lib/chef/knife/solo_prepare.rb:57:in `run'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/chef-13.2.20/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/chef-13.2.20/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/chef-13.2.20/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/chef-13.2.20/lib/chef/knife.rb:219:in `run'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/chef-13.2.20/lib/chef/application/knife.rb:156:in `run'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/gems/chef-13.2.20/bin/knife:25:in `<top (required)>'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/bin/knife:23:in `load'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/bin/knife:23:in `<main>'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/bin/ruby_executable_hooks:15:in `eval'
	from /Users/wbotelhos/.rvm/gems/ruby-2.4.1@app-chef/bin/ruby_executable_hooks:15:in `<main>'
```

## Debug

```ruby
require  'openssl'

dh = OpenSSL::PKey::DH.new

dh.p
# nil

dh.p = 'foo'

# NoMethodError: undefined method `p=' for #<OpenSSL::PKey::DH:0x007f7f7500ad88>
```

Looks like `DH` has no `p` method. I could not find.

## Inside

`lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb`

The value for `p` is returned:

```
32317006071311007300338913926423828248817941241140239112842009751400741706634354222619689417363569347117901737909704191754605873209195028853758986185622153212175412514901774520270235796078236248884246189477587641105928646099411723245426622522193230540919037680524235519125679715870117001058055877651038861847280257976054903569732561526167081339361799541336476539160368317896729073178384589680639671900977202194168647225871031411336429319536193471636533209717077448227988588565369208645296636077250268955505928362751121174096972998068410554359584866583291642136218231078990999448652468262416972035911852507045361090559
```

But `OpenSSL::PKey::DH.new` has no method `p`:

```
dh.p, dh.g = get_parameters
```

Thank you!

**Comment by mfazekas** [comment]
Hi any reason for using 3.2? 
Can you try with 4.1.0?

**Comment by perlun** [comment]
`knife-solo` 0.6.0 has a pessimistic dependency on net-ssh, <4. But `0.7.0.pre` seems to solve this: https://rubygems.org/gems/knife-solo/versions/0.7.0.pre

0.6.0 works correctly on Ruby 2.3 for me, but not on Ruby 2.4 (I get the same error).

With 0.7.0.pre it works correctly on Ruby 2.4 also. I suggest the issue be closed as a "known issue" with older net-ssh and Ruby 2.4.

**Comment by wbotelhos** [comment]
Using `knife-solo 0.7.0.pre` `net-ssh` goes to `2.4.1` and now works with `ruby 2.4.1`. (:

Thank you @mfazekas and @perlun for the solution. <3

**Comment by rilian** [comment]
we've suddenly got exactly same issue with our Capistrano-3 based deploys on Codeship, while locally everything works fine.

upgrading net-ssh fixed the issue

```
bundle update net-ssh
...
Installing net-ssh 5.1.0 (was 2.9.4)
```

**Comment by c80609a** [comment]
Pathed  `.gitlab-ci.yml`, gitlab runner (docker executor):

```
.prepare_deploy: &prepare_deploy
  before_script:
    - bundle install -j $(nproc) --path vendor
    - bundle update net-ssh
    - which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)

[...rest of file..]
```

**Comment by zedtux** [comment]
I had this issue with Capistrano, when trying to deploy, with the 2.x version of that gem.

Upgrading to the version 4.2.0 solved the issue.

Thank you @rilian for suggesting it! 👍

**Comment by sreedhag** [comment]
Thanks @rilian !! Upgrade solved the issue.
