### PR TITLE
Refactor Object#=~ as it is deprecated since Ruby 2.6 and unsupported since Ruby 3.2

### PR DESCRIPTION
**Pull request by srbarrios**
As you can read [here](https://rubyreferences.github.io/rubychanges/3.2.html#removals), if we want that net-ssh still work in Ruby >= 3.2, we need to change `=~` by `match` method.

That's a quick PR addressing only that particular breaking change.
`test` Rake task pass, but you might want additional pre-condition that the object calling the method `match`, is not actually a `nil` object, otherwise it will raise an error. Let me know what do you think about it, but I could only see one place where that really was necessary.

### CODE REVIEW

**Comment by dentarg** [comment]
Is this solving a real life problem you are experiencing? I assume many net-ssh users are using net-ssh with Ruby 3.2 and 3.3.

`=~` hasn't been removed?

I think the change you have made could be risky

```ruby
$ RUBY_OPTS=-w ruby -e 'p RUBY_VERSION; nil =~ /foo/'
"3.3.4"

$ RUBY_OPTS=-w ruby -e 'p RUBY_VERSION; nil.match?(/foo/)'
"3.3.4"
-e:1:in `<main>': undefined method `match?' for nil (NoMethodError)

p RUBY_VERSION; nil.match?(/foo/)
                   ^^^^^^^
```

**Comment by dentarg** [comment]
I think the actual problem, where this happens, should be found and addressed

```ruby
$ RUBY_OPTS=-w ruby -e 'p RUBY_VERSION; Object.new =~ /foo/'
"3.3.4"
-e:1:in `<main>': undefined method `=~' for an instance of Object (NoMethodError)
```

Just switching to `#match?` will still fail equally hard?

```ruby
$ RUBY_OPTS=-w ruby -e 'p RUBY_VERSION; Object.new.match?(/foo/)'
"3.3.4"
-e:1:in `<main>': undefined method `match?' for an instance of Object (NoMethodError)

p RUBY_VERSION; Object.new.match?(/foo/)
                          ^^^^^^^
```

**Comment by mfazekas** [comment]
@srbarrios  thanks much the PR

>if we want that net-ssh still work in Ruby >= 3.2, we need to change =~ by match method.
I think this statement is misleading.
 
`=~` is working fine in Ruby >= 3.2, we expect the left side to be `string` in most of code changed. Sorry  this PR sounds a bit like cargo culting. If you see specific issue with `=~` that's another issue, and we're happy to address that, but as I currently see it just adds changes, which could either improve or make things worse. Thanks for the understanding.

**Comment by srbarrios** [comment]
Sorry guys, I misunderstood the issue I was facing, all good.
Thanks for the fast replies.
